### ISSUE TITLE
Routing algorithm

### ISSUE THREAD

**Issue by dsluijk** [ip-v8/ipv8-docs#5]
It would be nice if the protocol had a good algorithm to send messages to peers without direct communication. The issue here is to have an efficient method of finding a path to the desired peer in the network without flooding it too much. There is a great chance this has been designed before, so we need to look into that first.

To get started we can look into the following:
 - [Kademlia](http://www.scs.stanford.edu/~dm/home/papers/kpos.pdf)
 - [Cjdns](https://github.com/cjdelisle/cjdns/)
 - [Barabási–Albert model](https://en.wikipedia.org/wiki/Barabási–Albert_model)
 - [Scale-free network](https://en.wikipedia.org/wiki/Scale-free_network)
 - [Small-world network](https://en.wikipedia.org/wiki/Small-world_network)
 - [Pastry](https://link.springer.com/content/pdf/10.1007%2F3-540-45518-3_18.pdf)
 - [IPFS](https://github.com/ipfs/papers/blob/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf)

**Comment by dsluijk** [comment]
I ran two simple tests with a small world network.
Due to resource constraints this is ran against `1250` nodes, with a rewire probability of `0.3`.

The two tests were run with `4` connections and `20` connections per node.
Here are the results:

![Screenshot from 2019-05-25 14-41-01](https://user-images.githubusercontent.com/8537327/58386882-68ec8180-8006-11e9-92fe-dcad11ccb116.png)
With `4` connections the average path length was `6.352`.

![Screenshot from 2019-05-25 15-52-43](https://user-images.githubusercontent.com/8537327/58386888-6ee26280-8006-11e9-9ce8-ef767d751aec.png)
With `20` connections the average path length was `2.88`.

These results look really promising, and I will do more extensive tests in the next week or so.

**Comment by NULLx76** [comment]
[IPFS Whitepaper](https://github.com/ipfs/ipfs/blob/master/papers/ipfs-cap2pfs/ipfs-p2p-file-system.pdf): May contain some useful things.

**Comment by dsluijk** [comment]
An attempt to model a large network is being worked on in [ip-v8/pathfinder](https://github.com/ip-v8/pathfinder)

**Comment by dsluijk** [comment]
Closed in favor of https://github.com/Tribler/tribler/issues/4658
